//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANG_LUONG
    {
        public int LUONG_ID { get; set; }
        public int USER_ID { get; set; }
        public string LUONG_CO_BAN { get; set; }
        public string LUONG_BAO_HIEM { get; set; }
        public string PHU_CAP_AN_TRUA { get; set; }
        public string PHU_CAP_DI_LAI_DIEN_THOAI { get; set; }
        public string PHU_CAP_THUONG_DOANH_SO { get; set; }
        public string PHU_CAP_TRACH_NHIEM { get; set; }
        public string CONG_CO_BAN { get; set; }
        public string CONG_CO_BAN_NGAY { get; set; }
        public string CONG_CO_BAN_GIO { get; set; }
        public string BAO_HIEM_CONG_TY { get; set; }
        public string BAO_HIEM_NHAN_VIEN { get; set; }
        public string LUONG_THUC_TE_CONG_LAM_THUC { get; set; }
        public string LUONG_THUC_TE_SO_TIEN { get; set; }
        public string LUONG_LAM_THEM_CONG_NGAY_THUONG { get; set; }
        public string LUONG_LAM_THEM_TIEN_CONG_NGAY_THUONG { get; set; }
        public string LUONG_LAM_THEM_CONG_NGAY_NGHI { get; set; }
        public string LUONG_LAM_THEM_TIEN_CONG_NGAY_NGHI { get; set; }
        public string LUONG_LAM_THEM_CONG_NGAY_LE { get; set; }
        public string LUONG_LAM_THEM_TIEN_CONG_NGAY_LE { get; set; }
        public string TONG_TIEN_CONG { get; set; }
        public string TAM_UNG { get; set; }
        public string GIO_DI_TRE { get; set; }
        public string PHAT_DI_TRE { get; set; }
        public string CONG_DOAN { get; set; }
        public string LUONG_LAO_CONG { get; set; }
        public string THUC_LINH { get; set; }
        public string THANG_LINH_LUONG { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
