//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BORROWING_PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BORROWING_PRODUCTS()
        {
            this.RETURNING_PRODUCTS = new HashSet<RETURNING_PRODUCTS>();
        }
    
        public int ID_HANG_MUON { get; set; }
        public string MA_HANG_HT { get; set; }
        public string KHO_MUON { get; set; }
        public System.DateTime NGAY_MUON { get; set; }
        public int SL_MUON { get; set; }
        public string MA_PHIEU_XUAT_KHO { get; set; }
        public string TRANG_THAI { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETURNING_PRODUCTS> RETURNING_PRODUCTS { get; set; }
    }
}
