//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.CUSTOMER_ACCOUNTS = new HashSet<CUSTOMER_ACCOUNTS>();
            this.CUSTOMER_CONTACTS = new HashSet<CUSTOMER_CONTACTS>();
            this.HOLD_PRODUCT_DETAILS = new HashSet<HOLD_PRODUCT_DETAILS>();
            this.MANAGE_SALES_AND_CUSTOMERS = new HashSet<MANAGE_SALES_AND_CUSTOMERS>();
        }
    
        public string MA_KHACH_HANG { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public string DIA_CHI_CONG_TY { get; set; }
        public string DIA_CHI_XUAT_HOA_DON { get; set; }
        public string MA_NHOM_KHACH { get; set; }
        public string MST { get; set; }
        public string DIEN_THOAI { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string WEBSITE { get; set; }
        public int USER_ID { get; set; }
        public string MO_TA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_ACCOUNTS> CUSTOMER_ACCOUNTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_CONTACTS> CUSTOMER_CONTACTS { get; set; }
        public virtual CUSTOMER_GROUPS CUSTOMER_GROUPS { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLD_PRODUCT_DETAILS> HOLD_PRODUCT_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANAGE_SALES_AND_CUSTOMERS> MANAGE_SALES_AND_CUSTOMERS { get; set; }
    }
}
