//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLD_PRODUCT_DETAILS
    {
        public int ID_GIU_HANG { get; set; }
        public int NHAN_VIEN_GIU { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public Nullable<int> SL_GIU { get; set; }
        public string LOAI_GIU { get; set; }
        public string TRANG_THAI { get; set; }
        public string MA_PHIEU_XUAT_KHO { get; set; }
        public string MA_KHACH_XUAT_KHO { get; set; }
        public Nullable<int> SL_XUAT_KHO { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual HOLD_PRODUCTS HOLD_PRODUCTS { get; set; }
        public virtual USER USER { get; set; }
    }
}
