//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLD_PRODUCTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOLD_PRODUCTS()
        {
            this.HOLD_PRODUCT_DETAILS = new HashSet<HOLD_PRODUCT_DETAILS>();
        }
    
        public int ID_GIU_HANG { get; set; }
        public string MA_HANG_HT { get; set; }
        public Nullable<System.DateTime> NGAY_GIU { get; set; }
        public Nullable<int> TONG_SO_GIU { get; set; }
        public Nullable<int> SL_GIU_DA_XUAT { get; set; }
        public Nullable<int> SL_GIU_CHUA_XU_LY { get; set; }
        public string TRANG_THAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLD_PRODUCT_DETAILS> HOLD_PRODUCT_DETAILS { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
