//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIST_PERMISSIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIST_PERMISSIONS()
        {
            this.USER_PERMISSION = new HashSet<USER_PERMISSION>();
        }
    
        public int PERMISSION_ID { get; set; }
        public string PERMISSION_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONTROLLER_ID { get; set; }
    
        public virtual LIST_CONTROLLERS LIST_CONTROLLERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_PERMISSION> USER_PERMISSION { get; set; }
    }
}
