//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_TERMS
    {
        public string MA_DIEU_KHOAN { get; set; }
        public string TEN_DIEU_KHOAN { get; set; }
        public string NOI_DUNG_DIEU_KHOAN { get; set; }
        public string GHI_CHU { get; set; }
    }
}
