//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.HOLD_PRODUCTS = new HashSet<HOLD_PRODUCTS>();
            this.PURCHASE_ORDER = new HashSet<PURCHASE_ORDER>();
            this.TRANSFER_WAREHOUSE_PRODUCTS = new HashSet<TRANSFER_WAREHOUSE_PRODUCTS>();
        }
    
        public string MA_HANG_HT { get; set; }
        public string MA_HANG_NHAP { get; set; }
        public string TEN_HANG { get; set; }
        public string MA_CHI_TIET_NHOM_HANG { get; set; }
        public string SERI { get; set; }
        public string DON_VI_TINH { get; set; }
        public string NGUON_GOC { get; set; }
        public Nullable<byte> MODEL_DAC_BIET { get; set; }
        public Nullable<int> THOI_HAN_BAO_HANG { get; set; }
        public string MA_KHO { get; set; }
        public string DIEN_GIAI_KHI_MUA { get; set; }
        public string DIEN_GIAI_KHI_BAN { get; set; }
        public string DAC_TINH { get; set; }
        public int SL_TON_KHO { get; set; }
        public int SL_DANG_GIU { get; set; }
        public int SL_CO_THE_DUNG { get; set; }
        public Nullable<decimal> DON_GIA_MUA_CO_DINH { get; set; }
        public Nullable<decimal> DON_GIA_MUA_GAN_NHAT { get; set; }
        public byte[] HINH_ANH { get; set; }
        public string GHI_CHU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLD_PRODUCTS> HOLD_PRODUCTS { get; set; }
        public virtual PRODUCT_CATEGORY_DETAILS PRODUCT_CATEGORY_DETAILS { get; set; }
        public virtual PRODUCT_META PRODUCT_META { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE_ORDER> PURCHASE_ORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSFER_WAREHOUSE_PRODUCTS> TRANSFER_WAREHOUSE_PRODUCTS { get; set; }
    }
}
