//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETURNING_PRODUCTS
    {
        public int ID_HANG_TRA { get; set; }
        public int ID_HANG_MUON { get; set; }
        public System.DateTime NGAY_TRA { get; set; }
        public int SL_TRA { get; set; }
        public string KHO_TRA { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual BORROWING_PRODUCTS BORROWING_PRODUCTS { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
