//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_ACCOUNTS
    {
        public int ID_TAI_KHOAN_NCC { get; set; }
        public string MA_NCC { get; set; }
        public string SO_TAI_KHOAN { get; set; }
        public string TEN_NGAN_HANG { get; set; }
        public string CHI_NHANH { get; set; }
        public string TINH_TP { get; set; }
    
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
