//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPPLIER()
        {
            this.SUPPLIER_ACCOUNTS = new HashSet<SUPPLIER_ACCOUNTS>();
            this.SUPPLIER_CONTACTS = new HashSet<SUPPLIER_CONTACTS>();
        }
    
        public string MA_NCC { get; set; }
        public string TEN_NCC { get; set; }
        public string DIA_CHI { get; set; }
        public string SDT { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string MST { get; set; }
        public string MA_NHOM_HANG { get; set; }
        public string WEBSITE { get; set; }
        public int USER_ID { get; set; }
        public string MO_TA { get; set; }
    
        public virtual PRODUCT_CATEGORIES PRODUCT_CATEGORIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_ACCOUNTS> SUPPLIER_ACCOUNTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER_CONTACTS> SUPPLIER_CONTACTS { get; set; }
        public virtual USER USER { get; set; }
    }
}
