//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSFER_WAREHOUSE_PRODUCTS
    {
        public int ID_KY_GUI { get; set; }
        public string MA_HANG_HT { get; set; }
        public Nullable<System.DateTime> NGAY_KY_GUI { get; set; }
        public string KHO_NGUON { get; set; }
        public Nullable<int> SL_KY_GUI { get; set; }
        public string KHO_DICH { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
