//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PERMISSION
    {
        public int PERMISSION_ID { get; set; }
        public int USER_ID { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual LIST_PERMISSIONS LIST_PERMISSIONS { get; set; }
        public virtual USER USER { get; set; }
    }
}
