//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYSTEM_MANAGEMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_METAS
    {
        public int USER_ID { get; set; }
        public string DEPARTMENT_ID { get; set; }
        public string SEX { get; set; }
        public System.DateTime BIRTHDAY { get; set; }
        public System.DateTime START_TIME { get; set; }
        public string NUMBER_PHONE { get; set; }
        public string SENIORITY { get; set; }
        public string NATIVE_LAND { get; set; }
        public string LITERACY { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual USER USER { get; set; }
    }
}
